title: Minimizing Regret
logo: https://raw.githubusercontent.com/MinRegret/deluca/dev/assets/img/deluca.svg?token=AAURLVRRLKHPK4VELPKH6X27RW5LC
description: Google Princeton AI and Hazan Lab @ Princeton University
show_downloads: false
theme: jekyll-theme-minimal
authors: ["elad"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tags: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      tags: false

google_analytics:
