title: Minimizing Regret
logo: https://raw.githubusercontent.com/MinRegret/deluca/dev/assets/img/deluca.svg?token=AAURLVRRLKHPK4VELPKH6X27RW5LC
description: Google Princeton AI and Hazan Lab @ Princeton University
show_downloads: false
theme: jekyll-theme-minimal
author:
  name: Elad Hazan
  email: ehazan@cs.princeton.edu
  web: http://www.cs.princeton.edu/~ehazan

google_analytics:
